In [1]:
%load_ext autoreload
%autoreload 2

import pickle
import pandas as pd
import numpy as np
import altair

In [2]:
low_level_ontology_eval = pickle.load(open('ragas_eval/low_level_ontology_eval_11_8.pkl', 'rb'))
high_level_ontology_eval = pickle.load(open('ragas_eval/high_level_ontology_eval_11_8.pkl', 'rb'))
full_ontology_eval = pickle.load(open('ragas_eval/full_ontology_eval_11_8.pkl', 'rb'))
rag_eval = pickle.load(open('ragas_eval/rag_eval_11_8.pkl', 'rb'))

low_level_ontology_eval_no_defs = pickle.load(open('ragas_eval/low_level_ontology_eval_no_defs.pkl', 'rb'))
high_level_ontology_eval_no_defs = pickle.load(open('ragas_eval/high_level_ontology_eval_no_defs.pkl', 'rb'))
full_ontology_eval_no_defs = pickle.load(open('ragas_eval/full_ontology_eval_no_defs.pkl', 'rb'))

sci_categories_eval = pickle.load(open('ragas_eval/sci_categories_eval.pkl', 'rb'))
sci_subcategories_eval = pickle.load(open('ragas_eval/sci_subcategories_eval.pkl', 'rb'))
sci_full_eval = pickle.load(open('ragas_eval/sci_full_eval.pkl', 'rb'))
sci_rag_eval = pickle.load(open('ragas_eval/sci_rag_eval.pkl', 'rb'))

/shared/viz/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# Prepare data for Response Groundedness chart
groundedness_data = [
    {
        'Domain': 'CLBP',
        'Ontology': 'Full Ontology',
        'Score': np.mean(full_ontology_eval_no_defs['results']['nv_response_groundedness'])
    },
    {
        'Domain': 'CLBP',
        'Ontology': 'Fine-grained',
        'Score': np.mean(low_level_ontology_eval_no_defs['results']['nv_response_groundedness'])
    },
    {
        'Domain': 'CLBP',
        'Ontology': 'Coarse-grained',
        'Score': np.mean(high_level_ontology_eval_no_defs['results']['nv_response_groundedness'])
    },
    {
        'Domain': 'CLBP',
        'Ontology': 'RAG (No Ontology)',
        'Score': np.mean(rag_eval['results']['nv_response_groundedness'])
    },
    {
        'Domain': 'SCI',
        'Ontology': 'Full Ontology',
        'Score': np.mean(sci_full_eval['results']['nv_response_groundedness'])
    },
    {
        'Domain': 'SCI',
        'Ontology': 'Fine-grained',
        'Score': np.mean(sci_subcategories_eval['results']['nv_response_groundedness'])
    },
    {
        'Domain': 'SCI',
        'Ontology': 'Coarse-grained',
        'Score': np.mean(sci_categories_eval['results']['nv_response_groundedness'])
    },
    {
        'Domain': 'SCI',
        'Ontology': 'RAG (No Ontology)',
        'Score': np.mean(sci_rag_eval['results']['nv_response_groundedness'])
    }
]

groundedness_df = pd.DataFrame(groundedness_data)
groundedness_df

  Domain           Ontology     Score
0   CLBP      Full Ontology  0.529310
1   CLBP       Fine-grained  0.546552
2   CLBP     Coarse-grained  0.343103
3   CLBP  RAG (No Ontology)  0.586207
4    SCI      Full Ontology  0.758065
5    SCI       Fine-grained  0.681452
6    SCI     Coarse-grained  0.766129
7    SCI  RAG (No Ontology)  0.689516

In [4]:
# Prepare data for Context Relevance chart
relevance_data = [
    {
        'Domain': 'CLBP',
        'Ontology': 'Full Ontology',
        'Score': np.mean(full_ontology_eval_no_defs['results']['nv_context_relevance'])
    },
    {
        'Domain': 'CLBP',
        'Ontology': 'Fine-grained',
        'Score': np.mean(low_level_ontology_eval_no_defs['results']['nv_context_relevance'])
    },
    {
        'Domain': 'CLBP',
        'Ontology': 'Coarse-grained',
        'Score': np.mean(high_level_ontology_eval_no_defs['results']['nv_context_relevance'])
    },
    {
        'Domain': 'CLBP',
        'Ontology': 'RAG (No Ontology)',
        'Score': np.mean(rag_eval['results']['nv_context_relevance'])
    },
    {
        'Domain': 'SCI',
        'Ontology': 'Full Ontology',
        'Score': np.mean(sci_full_eval['results']['nv_context_relevance'])
    },
    {
        'Domain': 'SCI',
        'Ontology': 'Fine-grained',
        'Score': np.mean(sci_subcategories_eval['results']['nv_context_relevance'])
    },
    {
        'Domain': 'SCI',
        'Ontology': 'Coarse-grained',
        'Score': np.mean(sci_categories_eval['results']['nv_context_relevance'])
    },
    {
        'Domain': 'SCI',
        'Ontology': 'RAG (No Ontology)',
        'Score': np.mean(sci_rag_eval['results']['nv_context_relevance'])
    }
]

relevance_df = pd.DataFrame(relevance_data)
relevance_df

  Domain           Ontology     Score
0   CLBP      Full Ontology  0.218966
1   CLBP       Fine-grained  0.306897
2   CLBP     Coarse-grained  0.118966
3   CLBP  RAG (No Ontology)  0.550000
4    SCI      Full Ontology  0.447581
5    SCI       Fine-grained  0.366935
6    SCI     Coarse-grained  0.431452
7    SCI  RAG (No Ontology)  0.435484

In [5]:
combined_data = []

# Add groundedness data
for item in groundedness_data:
    combined_data.append({
        'Domain': item['Domain'],
        'Ontology': item['Ontology'],
        'Metric': 'Response Groundedness',
        'Score': item['Score']
    })

# Add relevance data
for item in relevance_data:
    combined_data.append({
        'Domain': item['Domain'],
        'Ontology': item['Ontology'],
        'Metric': 'Context Relevance',
        'Score': item['Score']
    })

combined_df = pd.DataFrame(combined_data)
combined_df

   Domain           Ontology                 Metric     Score
0    CLBP      Full Ontology  Response Groundedness  0.529310
1    CLBP       Fine-grained  Response Groundedness  0.546552
2    CLBP     Coarse-grained  Response Groundedness  0.343103
3    CLBP  RAG (No Ontology)  Response Groundedness  0.586207
4     SCI      Full Ontology  Response Groundedness  0.758065
5     SCI       Fine-grained  Response Groundedness  0.681452
6     SCI     Coarse-grained  Response Groundedness  0.766129
7     SCI  RAG (No Ontology)  Response Groundedness  0.689516
8    CLBP      Full Ontology      Context Relevance  0.218966
9    CLBP       Fine-grained      Context Relevance  0.306897
10   CLBP     Coarse-grained      Context Relevance  0.118966
11   CLBP  RAG (No Ontology)      Context Relevance  0.550000
12    SCI      Full Ontology      Context Relevance  0.447581
13    SCI       Fine-grained      Context Relevance  0.366935
14    SCI     Coarse-grained      Context Relevance  0.431452
15    SCI  RAG (No Ontology)      Context Relevance  0.435484

In [6]:
base = altair.Chart(combined_df).encode(
    x=altair.X('Ontology:N', title='Ontology Level', axis=altair.Axis(labelFontWeight='bold')),
    y=altair.Y('Score:Q', title=None, scale=altair.Scale(domain=[0, 1]), axis=altair.Axis(grid=False)),
    color=altair.Color('Ontology:N', title='Ontology Level', legend=None, scale=altair.Scale(scheme='tableau10'))
)

bars = base.mark_bar()

text = base.mark_text(
    align='center',
    baseline='bottom',
    dy=-5,
    fontWeight='bold',
    color='black',
    fontSize=16
).encode(
    text=altair.Text('Score:Q', format='.3f')
)

combined_chart = (bars + text).properties(
    width=200,
    height=250
).facet(
    column=altair.Column('Domain:N', title=None, header=altair.Header(labelFontWeight='bold', labelFontSize=14)),
    row=altair.Row('Metric:N', title=None, header=altair.Header(labelFontWeight='bold', labelFontSize=14))
)

combined_chart

alt.FacetChart(...)

In [7]:
combined_chart.save('figs/rag_perf.png', ppi=500)

# Analyzing Definitions vs No Definitions

In [8]:
# Prepare data in long format for Altair
definitions_groundedness = [
    {
        'Treatment': 'Descriptions',
        'Level': 'Fine-grained',
        'Score': np.mean(low_level_ontology_eval['results']['nv_response_groundedness'])
    },
    {
        'Treatment': 'Descriptions',
        'Level': 'Coarse-grained',
        'Score': np.mean(high_level_ontology_eval['results']['nv_response_groundedness'])
    },
    {
        'Treatment': 'Descriptions',
        'Level': 'Full Ontology',
        'Score': np.mean(full_ontology_eval['results']['nv_response_groundedness'])
    },
    {
        'Treatment': 'No Descriptions',
        'Level': 'Fine-grained',
        'Score': np.mean(low_level_ontology_eval_no_defs['results']['nv_response_groundedness'])
    },
    {
        'Treatment': 'No Descriptions',
        'Level': 'Coarse-grained',
        'Score': np.mean(high_level_ontology_eval_no_defs['results']['nv_response_groundedness'])
    },
    {
        'Treatment': 'No Descriptions',
        'Level': 'Full Ontology',
        'Score': np.mean(full_ontology_eval_no_defs['results']['nv_response_groundedness'])
    },
]

definitions_groundedness_df = pd.DataFrame(definitions_groundedness)
definitions_groundedness_df

         Treatment           Level     Score
0     Descriptions    Fine-grained  0.660345
1     Descriptions  Coarse-grained  0.570690
2     Descriptions   Full Ontology  0.584483
3  No Descriptions    Fine-grained  0.546552
4  No Descriptions  Coarse-grained  0.343103
5  No Descriptions   Full Ontology  0.529310

In [9]:
# Prepare data in long format for Altair
definitions_relevance_data = [
    {
        'Treatment': 'Descriptions',
        'Level': 'Fine-grained',
        'Score': np.mean(low_level_ontology_eval['results']['nv_context_relevance'])
    },
    {
        'Treatment': 'Descriptions',
        'Level': 'Coarse-grained',
        'Score': np.mean(high_level_ontology_eval['results']['nv_context_relevance'])
    },
    {
        'Treatment': 'Descriptions',
        'Level': 'Full Ontology',
        'Score': np.mean(full_ontology_eval['results']['nv_context_relevance'])
    },
    {
        'Treatment': 'No Descriptions',
        'Level': 'Fine-grained',
        'Score': np.mean(low_level_ontology_eval_no_defs['results']['nv_context_relevance'])
    },
    {
        'Treatment': 'No Descriptions',
        'Level': 'Coarse-grained',
        'Score': np.mean(high_level_ontology_eval_no_defs['results']['nv_context_relevance'])
    },
    {
        'Treatment': 'No Descriptions',
        'Level': 'Full Ontology',
        'Score': np.mean(full_ontology_eval_no_defs['results']['nv_context_relevance'])
    },
]

definitions_relevance_data_df = pd.DataFrame(definitions_relevance_data)
definitions_relevance_data_df

         Treatment           Level     Score
0     Descriptions    Fine-grained  0.444828
1     Descriptions  Coarse-grained  0.370690
2     Descriptions   Full Ontology  0.253448
3  No Descriptions    Fine-grained  0.306897
4  No Descriptions  Coarse-grained  0.118966
5  No Descriptions   Full Ontology  0.218966

In [10]:
combined_data_defs = []

# Add groundedness data
for item in definitions_groundedness:
    combined_data_defs.append({
        'Treatment': item['Treatment'],
        'Level': item['Level'],
        'Metric': 'Response Groundedness',
        'Score': item['Score']
    })

# Add relevance data
for item in definitions_relevance_data:
    combined_data_defs.append({
        'Treatment': item['Treatment'],
        'Level': item['Level'],
        'Metric': 'Context Relevance',
        'Score': item['Score']
    })

combined_data_defs_df = pd.DataFrame(combined_data_defs)
combined_data_defs_df

          Treatment           Level                 Metric     Score
0      Descriptions    Fine-grained  Response Groundedness  0.660345
1      Descriptions  Coarse-grained  Response Groundedness  0.570690
2      Descriptions   Full Ontology  Response Groundedness  0.584483
3   No Descriptions    Fine-grained  Response Groundedness  0.546552
4   No Descriptions  Coarse-grained  Response Groundedness  0.343103
5   No Descriptions   Full Ontology  Response Groundedness  0.529310
6      Descriptions    Fine-grained      Context Relevance  0.444828
7      Descriptions  Coarse-grained      Context Relevance  0.370690
8      Descriptions   Full Ontology      Context Relevance  0.253448
9   No Descriptions    Fine-grained      Context Relevance  0.306897
10  No Descriptions  Coarse-grained      Context Relevance  0.118966
11  No Descriptions   Full Ontology      Context Relevance  0.218966

In [11]:
base = altair.Chart(combined_data_defs_df).encode(
    x=altair.X('Level:N', title='Ontology Level', axis=altair.Axis(labelFontWeight='bold')),
    y=altair.Y('Score:Q', title=None, scale=altair.Scale(domain=[0, 1]), axis=altair.Axis(grid=False)),
    color=altair.Color('Level:N', title='Ontology Level', legend=None, scale=altair.Scale(scheme='tableau10'))
)

bars = base.mark_bar()

text = base.mark_text(
    align='center',
    baseline='bottom',
    dy=-5,
    fontWeight='bold',
    color='black',
    fontSize=16
).encode(
    text=altair.Text('Score:Q', format='.3f')
)

combined_data_defs_chart = (bars + text).properties(
    width=200,
    height=250
).facet(
    column=altair.Column('Treatment:N', title=None, header=altair.Header(labelFontWeight='bold', labelFontSize=14)),
    row=altair.Row('Metric:N', title=None, header=altair.Header(labelFontWeight='bold', labelFontSize=14))
)

combined_data_defs_chart

alt.FacetChart(...)

In [12]:
combined_data_defs_chart.save("figs/rag_defs_perf.png", ppi=500)